apiVersion: v1
kind: Service
metadata:
  name: nginx
  namespace: tom
spec:
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30005
  type: NodePort