apiVersion: v1
kind: Service
metadata:
  name: grafana
  namespace: lens-metrics
  labels:
    app: grafana
spec:
  selector:
    app: grafana
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
      nodePort: 32000
  type: NodePort